"use client";

import { useMemo } from "react";
import Link from "next/link";
import { ArrowRight, Building2, FileText } from "lucide-react";
import { EmptyState } from "@/components/common/EmptyState";
import { ErrorState } from "@/components/common/ErrorState";
import { DashboardSkeleton } from "@/components/dashboard/DashboardSkeleton";
import { Button } from "@/components/ui/button";
import { PageContainer } from "@/components/layout/PageContainer";
import { PrintStyles } from "./PrintStyles";
import { ReportHeader } from "./ReportHeader";
import { ReportSidebar } from "./ReportSidebar";
import { ReportSection } from "./ReportSection";
import { REPORT_SECTIONS, type ReportSectionKey } from "./sections";
import {
  AnalyticsSummarySection,
  BusinessDnaSection,
  BusinessHealthSection,
  BusinessProfileSection,
  BusinessScoresSection,
  ExecutiveSummarySection,
  IntelligenceSummarySection,
  OpportunitySummarySection,
  RecommendationSummarySection,
  RiskSummarySection,
  RoadmapSummarySection,
  RuleSummarySection,
} from "./sections/index";
import { useReportsData, type ReportsData } from "./use-reports-data";

/**
 * Top-level Executive Reports view.
 *
 * Layout: sidebar TOC on the left (sticky, hidden on print),
 * report sections stacked on the right. The PrintStyles
 * component attaches a single @media print block that hides
 * the sidebar / header buttons and switches card surfaces to
 * a paper-friendly off-white when the user triggers browser
 * print. A small footer note renders on the printed page so
 * the reader knows the source.
 */
export function ReportsView() {
  const { state, refresh, isFetching } = useReportsData();

  const lastAnalyzedAt = useMemo<string | null>(() => {
    if (state.status !== "ready") return null;
    return (
      state.data.twin.last_analysis_at ??
      state.data.twin.generated_at ??
      state.data.recommendations.generated_at
    );
  }, [state]);

  if (state.status === "loading") {
    return (
      <PageContainer width="wide">
        <div className="flex flex-col gap-4">
          <DashboardSkeleton rows={3} />
          <DashboardSkeleton rows={3} />
          <DashboardSkeleton rows={5} />
          <DashboardSkeleton rows={4} />
          <DashboardSkeleton rows={6} />
        </div>
      </PageContainer>
    );
  }

  if (state.status === "no-business") {
    return (
      <PageContainer width="wide">
        <EmptyState
          icon={<Building2 className="size-6" aria-hidden="true" />}
          title="No business profile yet"
          description={
            state.detail ||
            "Set up your business profile to generate an executive report."
          }
          actionLabel="Create business profile"
          onAction={() => {
            if (typeof window !== "undefined") {
              window.location.href = "/business";
            }
          }}
        />
        <div className="mt-4 flex items-center justify-center">
          <Button asChild variant="ghost" size="sm">
            <Link href="/business">
              Go to Business
              <ArrowRight className="size-4" aria-hidden="true" />
            </Link>
          </Button>
        </div>
      </PageContainer>
    );
  }

  if (state.status === "error") {
    return (
      <PageContainer width="wide">
        <ErrorState
          title="Could not load the report"
          description={state.detail}
          actionLabel="Try again"
          onAction={refresh}
        />
      </PageContainer>
    );
  }

  return (
    <>
      <PrintStyles />
      <PageContainer width="wide">
        <div className="flex flex-col gap-4 lg:flex-row">
          <ReportSidebar />

          <div className="flex min-w-0 flex-1 flex-col gap-4">
            <ReportHeader
              lastAnalyzedAt={lastAnalyzedAt}
              isRefreshing={isFetching}
              onRefresh={refresh}
            />

            {REPORT_SECTIONS.map((meta) => (
              <Section
                key={meta.key}
                data={state.data}
                sectionKey={meta.key}
              />
            ))}

            <ReportFooter />
          </div>
        </div>
      </PageContainer>
    </>
  );
}

/**
 * Footer that prints at the end of the report. Visually
 * minimal on screen; the @media print block in PrintStyles
 * keeps it visible on the printed page so the reader can
 * tell the source.
 */
function ReportFooter() {
  return (
    <footer
      aria-label="Report footer"
      className="mt-2 flex flex-col items-start gap-1 rounded-xl border border-border bg-card px-4 py-3 text-xs text-muted-foreground"
    >
      <span className="inline-flex items-center gap-1.5">
        <FileText className="size-3.5" aria-hidden="true" />
        Generated by Atlas AI
      </span>
      <span>
        Data is sourced live from the existing analytical engines
        (Digital Twin, Roadmap, Recommendations, Scores, DNA, Rules,
        Decision, Intelligence). No derivations or re-calculations
        are performed on top of the upstream payloads.
      </span>
    </footer>
  );
}

/**
 * Internal: maps a section key to its concrete section
 * component. `REPORT_SECTIONS` is the single source of truth
 * for the section list — adding a new section is one entry
 * in `sections.ts` plus one branch here. The `never` cast
 * gives an exhaustiveness check at compile time.
 */
function Section({
  data,
  sectionKey,
}: {
  data: ReportsData;
  sectionKey: ReportSectionKey;
}) {
  switch (sectionKey) {
    case "business-profile":
      return <BusinessProfileSection data={data} />;
    case "executive-summary":
      return <ExecutiveSummarySection data={data} />;
    case "business-health":
      return <BusinessHealthSection data={data} />;
    case "business-scores":
      return <BusinessScoresSection data={data} />;
    case "business-dna":
      return <BusinessDnaSection data={data} />;
    case "intelligence-summary":
      return <IntelligenceSummarySection data={data} />;
    case "rule-summary":
      return <RuleSummarySection data={data} />;
    case "recommendation-summary":
      return <RecommendationSummarySection data={data} />;
    case "roadmap-summary":
      return <RoadmapSummarySection data={data} />;
    case "risk-summary":
      return <RiskSummarySection data={data} />;
    case "opportunity-summary":
      return <OpportunitySummarySection data={data} />;
    case "analytics-summary":
      return <AnalyticsSummarySection data={data} />;
    default: {
      const _exhaustive: never = sectionKey;
      return null;
    }
  }
}
